name: Test Coverage 

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the main branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cov:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4.2.0
    - uses: actions/setup-go@v5
      with:
        go-version: 1.22.2 # The Go version to download (if necessary) and use.
    - name: Get Coverage
      run: |
        go test ./... -timeout=30m -cover -coverprofile coverage.out
        cat coverage.out | grep -v ".pb.go" > coverage2.out
        cat coverage2.out | grep -v ".pb.gw.go" > coverage3.out
        go tool cover -func coverage3.out
        rm coverage2.out
        rm coverage.out
    - uses: codecov/codecov-action@v4.5.0
      with:
        token: ${{ secrets.CODECOV }}

